### ISSUE TITLE
Online check version?

### ISSUE THREAD

**Issue by Prisoner416** [mihaifm/HIBPOfflineCheck#14]
An online version of this tool would be greatly helpful for those that don't have the space for the raw file. The other keepass tool for Have I Been pwned doesn't make it easy to check a large batch of files like this one does.

**Comment by mihaifm** [comment]
Not a bad idea! It could be implemented as an option.

**Comment by sargue** [comment]
It's already been done: https://github.com/andrew-schofield/keepass2-haveibeenpwned

**Comment by jeff9315** [comment]
Sargue ... I use both, but the one by Andrew Schofield isn't nearly as useful because it doesn't allow you to use the information it provides outside of a dialog box. That means it can't be sorted, or looked at at a later date. On the other hand, it IS online so potentially might have more up-to-date pwned data.

I would LOVE to soo HIBP offline have an online option which would give us the best of both worlds.

**Comment by mihaifm** [comment]
Feature implemented: Added Online mode that can be activated in the options. Cheers!
